version: "3"

services:

    database:
      image: mysql:5.7
      container_name: database
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: challenge
      networks:
        - app-network

    # app: 
    #   build: ./
    #   restart: always
    #   env_file: 
    #     - .env
    #   ports:
    #     - 3000:3000
    #   container_name: app
    #   networks:
    #     - app-network
    #   depends_on:
    #     - database

networks:
  app-network:
    driver: bridge