version: "3"

services:

    database_challenge:
        image: mysql:5.7
        ports:
            - 3307:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_DATABASE: challenge
        container_name: database_challenge